version: '3.8'

services:
  caddy:
    image: blackmini/caddyf
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - TZ=Asia/Shanghai

  zns:
    image: blackmini/zns
    container_name: zns
    restart: unless-stopped
    expose:
      - "443"
    volumes:
      - ./data:/data
      - /var/www/html:/var/www/html
    environment:
      - TZ=Asia/Shanghai
    command: >
      ./zns
      -db /data/zns.db
      -root /var/www/html
      -h12 :443
      -h3 :443
      -upstream https://doh.pub/dns-query

volumes:
  caddy_data:
  caddy_config:
  data: